language: r

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: true

r:
  - release
  - devel

apt_packages:
 - default-jre
 - default-jdk
 - libopenbabel-dev
 
r_binary_packages:
 - RUnit
 - testthat

r_packages:
 - rlang
 - digest
 - devtools
 
bioc_packages:
 - survival
 - Rdisop
 - ChemmineOB
 
notifications:
  email:
    on_success: change
    on_failure: change
    
after_success:
  - Rscript -e 'covr::codecov()'